project:
  type: book
  output-dir: docs

book:
  title: "Анализ спа-центра"
  author: "Костыря Владимир"
  date: "10.09.2022"
  page-navigation: true
  page-footer: "Ногинск 2022, Костыря Владимир"
  cover-image: logo.png
  chapters:
    - index.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    df-print: paged
    code-fold: true
    cover-image: logo.png
  pdf:
    documentclass: scrreport

editor: visual

