<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Анализ спа-центра - 1&nbsp; Журнал посещений</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Журнал посещений</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Анализ спа-центра</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Начало работы</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Журнал посещений</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#знакомство-с-данными" id="toc-знакомство-с-данными" class="nav-link active" data-scroll-target="#знакомство-с-данными"><span class="toc-section-number">1.1</span>  Знакомство с данными</a>
  <ul class="collapse">
  <li><a href="#переменная-сard_type_2" id="toc-переменная-сard_type_2" class="nav-link" data-scroll-target="#переменная-сard_type_2">Переменная <code>сard_type_2</code></a></li>
  <li><a href="#переменная-duration_visit" id="toc-переменная-duration_visit" class="nav-link" data-scroll-target="#переменная-duration_visit">Переменная <code>duration_visit</code></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Журнал посещений</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="знакомство-с-данными" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="знакомство-с-данными"><span class="header-section-number">1.1</span> Знакомство с данными</h2>
<p>Мы начнем с отчета, где фиксируются данные посещений спа-центра. В этом датафрейме мы имеем следующие данные:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 23
   id    сard_…¹ surname first…² last_…³ start_of_visit      end_of_visit       
   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dttm&gt;              &lt;dttm&gt;             
 1 &lt;NA&gt;  Not     Сауна … Голубая &lt;NA&gt;    2014-01-01 00:40:01 2014-01-01 00:40:57
 2 00008 Not     Мочалов Евгений &lt;NA&gt;    2014-01-01 02:08:32 2014-01-01 05:52:51
 3 &lt;NA&gt;  Not     Сауна … Голубая &lt;NA&gt;    2014-01-01 05:53:23 2014-01-01 07:15:09
 4 РП12  Not     Разовое Посеще… &lt;NA&gt;    2014-01-01 07:16:57 2014-01-01 07:18:08
 5 РП35  Not     Разовое Посеще… &lt;NA&gt;    2014-01-01 07:17:29 2014-01-01 07:18:07
 6 00465 А 8 пе… Плескач Николай Никола… 2014-01-01 10:04:33 2014-01-01 11:21:54
 7 00448 А10 Ль… Кукина  Вера    Иванов… 2014-01-01 10:23:23 2014-01-01 11:15:14
 8 00477 А 8 пе… Лежнин  Андрей  Алексе… 2014-01-01 10:46:00 2014-01-01 11:58:10
 9 00019 Разово… Разовое Посеще… &lt;NA&gt;    2014-01-01 10:52:28 2014-01-01 12:05:04
10 &lt;NA&gt;  Льготн… -       -       -       2014-01-01 10:55:35 2014-01-01 12:01:00
11 ГП1   Разово… Гостин… Прожив… &lt;NA&gt;    2014-01-01 11:32:42 2014-01-01 12:29:16
12 06155 Утро-Д… Семено… Юлия    Алекса… 2014-01-01 11:33:13 2014-01-01 13:15:43
13 00113 А10 Ль… Шаров   Алекса… Алекса… 2014-01-01 11:50:08 2014-01-01 13:12:30
14 00114 Льготн… Шаров   Алекса… Евгень… 2014-01-01 11:51:05 2014-01-01 13:11:36
15 ГП6   Бассей… Гостин… Прожив… &lt;NA&gt;    2014-01-01 11:52:15 2014-01-01 11:56:44
16 00118 Детски… Шаров   Илья    &lt;NA&gt;    2014-01-01 11:56:32 2014-01-01 13:12:40
17 00119 1 мес … Смирно… Алла    Геннад… 2014-01-01 12:02:42 2014-01-01 13:13:35
18 00061 Утро-Д… Василец Татьяна Иванов… 2014-01-01 12:11:40 2014-01-01 13:34:56
19 00060 Детски… Василец Михаил  Владис… 2014-01-01 12:11:55 2014-01-01 13:35:10
20 00059 Льготн… Пчелин… В       &lt;NA&gt;    2014-01-01 12:25:56 2014-01-01 13:48:52
# … with 16 more variables: id_key &lt;chr&gt;, duration_visit &lt;dbl&gt;,
#   date_start &lt;date&gt;, round_date_start &lt;date&gt;, year_start &lt;dbl&gt;,
#   month_start &lt;dbl&gt;, day_number_start &lt;dbl&gt;, wday_start &lt;dbl&gt;,
#   date_end &lt;date&gt;, round_date_end &lt;date&gt;, year_end &lt;dbl&gt;, month_endt &lt;dbl&gt;,
#   day_number_end &lt;dbl&gt;, wday_end &lt;dbl&gt;, сard_type_2 &lt;chr&gt;, segment &lt;chr&gt;, and
#   abbreviated variable names ¹​сard_type, ²​first_name, ³​last_name</code></pre>
</div>
</div>
<div class="callout-important callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Обратите внимание
</div>
</div>
<div class="callout-body-container callout-body">
<p>Данные за 2022 год предствалены до 2023-01-31 23:56:17</p>
</div>
</div>
<div class="callout-warning callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Внимание
</div>
</div>
<div class="callout-body-container callout-body">
<p>Хотелось бы напомнить, что с марта по июль 2020 года была пандемия COVID-19. Поэтому на все показатели 2020 нужно обращать внимание с учетом этого события.</p>
</div>
</div>
<p>В нашей таблице содержатся следующие столбцы:</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Заметка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Мы выделим наиболее важные для нашего понимания</p>
</div>
</div>
<ul>
<li><p><code>id</code> - номер карты</p></li>
<li><p><code>start_of_visit</code> - начало визита</p></li>
<li><p><code>end_of_visit</code> - окончание визита</p></li>
<li><p><code>duration_visit</code> - продолжительность визита (в минутах)</p></li>
<li><p><code>сard_type_2</code> - преобразованный тип абонемента</p></li>
<li><p><code>segment</code> - сегмент гостя</p></li>
</ul>
<p>В наших данных есть много пропущенных значений в переменной <code>id</code> и <code>сard_type_2.</code></p>
<p><strong>Есть несколько причин этого:</strong></p>
<ol type="1">
<li><p>В начале работы спа-центра были созданы карты <code>Сауна</code> и <code>Аноним</code>, к которым не привязывался номер карты</p></li>
<li><p>Отсутсвие названия абонемента в переменной сard_type_2 связано с тем, что по картам Сауна, оказывались услуги типа “Оформить визит”, которые не требуют продажи абонемента.</p></li>
</ol>
<p>Если мы посмотрим на данные, например, 2019 года, то такой проблемы не будет.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 23
  id    сard_t…¹ surname first…² last_…³ start_of_visit      end_of_visit       
  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dttm&gt;              &lt;dttm&gt;             
1 05334 #А4 24 … Митичк… Ирина   Валент… 2019-01-01 05:20:34 2019-01-01 06:43:33
2 305   Бассейн… Номер   305     Скидка… 2019-01-01 09:26:12 2019-01-01 10:13:15
3 401   Бассейн… Номер   401     Скидка… 2019-01-01 09:47:55 2019-01-01 10:51:22
4 401_1 Бассейн… Номер … Доп. м… 1       2019-01-01 09:48:24 2019-01-01 10:52:39
5 303   Бассейн… Номер   303     Скидка… 2019-01-01 10:42:39 2019-01-01 12:03:43
# … with 16 more variables: id_key &lt;chr&gt;, duration_visit &lt;dbl&gt;,
#   date_start &lt;date&gt;, round_date_start &lt;date&gt;, year_start &lt;dbl&gt;,
#   month_start &lt;dbl&gt;, day_number_start &lt;dbl&gt;, wday_start &lt;dbl&gt;,
#   date_end &lt;date&gt;, round_date_end &lt;date&gt;, year_end &lt;dbl&gt;, month_endt &lt;dbl&gt;,
#   day_number_end &lt;dbl&gt;, wday_end &lt;dbl&gt;, сard_type_2 &lt;chr&gt;, segment &lt;chr&gt;, and
#   abbreviated variable names ¹​сard_type, ²​first_name, ³​last_name</code></pre>
</div>
</div>
<section id="переменная-сard_type_2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="переменная-сard_type_2">Переменная <code>сard_type_2</code></h3>
<p>У нас есть переменная <code>сard_type_2.</code> Это перекодированная версия столбца <code>сard_type.</code></p>
<p>Эта операция нам понадобилась, чтобы привести к единому формату название абонементов, которые в разный период времени имели различные наименования, но по сути являлись одним и тем же.</p>
<p>Ниже мы посмотрим какая доля посещений приходится на каждый вид абонемента:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 31 × 2
   `Тип абонемента` `Доля %`
   &lt;chr&gt;               &lt;dbl&gt;
 1 Hard_12              23.2
 2 А8_pool               9.7
 3 А4_pool               9.5
 4 Hard_12_3             8.4
 5 Hard_3                8.3
 6 One_pool              6.5
 7 Not                   5.2
 8 Hard_1                4.9
 9 А5_pool               4.2
10 А10_pool              4.1
# … with 21 more rows</code></pre>
</div>
</div>
<p>22% посещений спа-центра приходится на годовой безлимитный абонемент. Стоит отметиь, что это абонементы “Серебро” и “Безлимитный”.</p>
<p>Давайте посмотрим на тоже самое, но в разрезе годов.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 31 × 11
   сard_…¹ `2014` `2015` `2016` `2017` `2018` `2019` `2020` `2021` `2022` `2023`
   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Free       0.5    2.5    2.8    3.3    4.1    4.2    1.3    2.5    2.8    2.2
 2 Hard_1     4.8    4.2    4.5    6.3    4.9    5      4.7    6      3.5    5.4
 3 Hard_12    5.8   11     16.1   20.6   20.8   21.8   28.8   36.4   42.8   34.6
 4 Hard_1…    3.4    3.8    7.8   11.3   14     16.7   15.3    5      0     NA  
 5 Hard_2     0.6    0.6    0.5    0     NA     NA     NA     NA      0.1    0.4
 6 Hard_3     5.2    6.7    6.4    7.7    8.8    9.3   10.5    9.8    9.6    9.8
 7 Hard_6     2.4    4.1    3.3    3.9    3.8    4.2    5.6    3.3    4.7   10.9
 8 Not       16.7   17.8   14.9    0.2    0.1   NA     NA     NA     NA     NA  
 9 One_bk     1.6    1.1    1.4    2.5    2.1    1.5    2      2.5    2.4    3.5
10 One_po…    2      2      3.5    5.8    5.2    7.9    7.6   11.2   11.1   12.9
# … with 21 more rows, and abbreviated variable name ¹​сard_type_2</code></pre>
</div>
</div>
<p>Здесь нужно отметить, что до 2016 года в спа-центре не было годовых безлимитных карт, но они есть в нашем отчете. Это проблема связана с тем, что вместо того, чтобы создать новые абонементы - переименовали старые. Это не сильно повлияет на наш отчет в дальнейшем. Но будем иметь это ввиду на будущее.</p>
<p>Кроме того, мы можем заметить, что до 2017 года наибольшая доля посещений приходилось на абонементы типа <code>А (А10, А5, А4 и прочее)</code>. Абонменты типа <code>Not</code>, с высокой долей вероятностью, - различные разовые посещения.</p>
<p>Визуализируем наши данные по типам карт. Предварительно уберем из данных все абонементы, которые имеют долю не менее 5% посещений в каждом годе.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="intro_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Мы видим, что доля посещений на безлимитные абонеменнты 12 мес увеличивается с каждым годом. Посмотрим, как это выглядит в абсолбтных цифрах. Выделим только пермеменную <code>Hard_12</code></p>
<div class="callout-important callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Обратите внимание
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Hard_12</code> - содержит в себе как карты типа “Серебро”, так и карты типа “Золото”. Мы объединили их по причине того, что карты “Золото” были убраны из продаж. То есть, часть аудитории в настоящее время пользуется обычными безлимитными годовыми абонмеентами, что отражается на доле посещений.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Вторыми по посещаемости в наших данных являются карты <code>А8_pool</code>. Думаю, что есть смысл посмотреть динамику посещений по всем картам типа <code>А</code> (за исключением групповых занятий).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что количество посещений по данным абонементам с каждый годом сокращается. С 2016 года это свзано с введением безлимитных абонементов.</p>
<p>Посмотрим на общее количесво посещений из года в год.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Максимальное количество посещений было в 2019 году. По остальным годам видно, что количество посещений варьируется от 57 323 в 2021 году до 62 580 в 2018 году.</p>
<p>Давайте посмотрим на динамику разовых посещений. Возьмем все разовые посещения. Исключим только групповые занятия.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что в данном случае, динамика разовых посещений положительная. Давайте посмотрим на структуру разовых посещений.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что разовые посещения в бассейн <code>One_pool</code> имеют наибольший вклад в единоразовых посещениях нашего комплекса.</p>
<p>Ранее мы смотрели на годовые абонемнты <code>Hard_12</code>, так как они имели наибольшую долю посещений. Было бы интересно посмотреть на все безлимитные абонементы.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Понятно, что большое количество посещений приходится на годовые абонементы. Но нам интересна динамика посещений и по другим безлимитным посещениям. Мы видим, что абонемент <code>Hard_3</code> пользуется большей популярностью, чем <code>Hard_6</code>.</p>
<p>Давайте теперь выделим все посещения абонеметов группы <code>А</code>, группы <code>Hard</code> и <code>One</code> (разовые).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Суммируем все посещения по типам абонементов.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Суммируем все посещения по типам абонементов в разрезе годов.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что основынми группами абонементов, по которым чаще всего ходят гости, являются:</p>
<ul>
<li><p>Безлимитные абонементы типа <code>Hard</code></p></li>
<li><p>Абонементы группа <code>А</code></p></li>
<li><p>Разовые абонементы <code>One</code></p></li>
</ul>
<p>Делать какие-либо выводы сейчас будет своевременно. Имеет смысл, полученные данные, рассматривать вместе с отчетом о продажах карт, к которому мы перейдем позже.</p>
</section>
<section id="переменная-duration_visit" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="переменная-duration_visit">Переменная <code>duration_visit</code></h3>
<section id="абонементы-группы-а" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="абонементы-группы-а">Абонементы группы <code>А</code></h4>
<p>В наших данных также имеется перменная, которая отражает продолжительность посещения спа-центра, Мы знаем, что абонементы группы <code>А</code> ограничены временм посещения 45 минут. Плюс время на переодевание. В среднем мы закладываем 80-90 минут на посещение бассейна нашими гостями. Давайте проверим так ли это в среднем:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  `Среднее время посещения` `Медианное время посещения` `Стандартное отклонение`
                      &lt;dbl&gt;                       &lt;dbl&gt;                    &lt;dbl&gt;
1                      80.0                          78                     26.9</code></pre>
</div>
</div>
<p>Посмотрим на график</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что среднее время равняется 80 минутам. Стандартное отклонение - 26.9 минут. Это связано с тем, что в данных есть ошибки. Также, мы можем наблюдать данные ошибки и на графике. Причины различны: от некорректной работы ПО до ошибки администратора.</p>
<p>Давайте скорректируем наши данные, а именно отсечем по 5% данных с каждого конца,</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Заметка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Таким образом, мы потерям часть информации, но уберем крайние значения. Скорее всего среднее и медиана изменятся не существенно, а графически мы получим более реальную картину.</p>
</div>
</div>
<div class="cell" data-layout-align="center">

</div>
<p>Наши крайние значения:</p>
<ul>
<li><p>Q1 = 55</p></li>
<li><p>Q4 = 113</p></li>
</ul>
<p>Посотрим как изменилось среднее, медиана и стандратное отклонение и сразу взгляним на график</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Среднее Медиана Стд.отклонение
    &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;
1    79.6      78           12.4</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что существенно изменилось только стандартное отклонение. Остальные показатели остались в пределах первоначальных значений.</p>
<p>Можно заключить, что, в целом, гости, которые посещели наш спа-центр по абонементам группы <code>А</code>, укладывались в рамки того времени, которое мы устанавливали.</p>
<p>Тоже самое должно быть характерно и для абонементов разового посещения в бассейн.</p>
</section>
<section id="абонементы-разового-посещения-в-бассейн" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="абонементы-разового-посещения-в-бассейн">Абонементы разового посещения в бассейн</h4>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  `Среднее время посещения` `Медианное время посещения` Станда…¹ 5% кв…² 95% к…³
                      &lt;dbl&gt;                       &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1                      86.6                          77     53.8      23     190
# … with abbreviated variable names ¹​`Стандартное отклонение`, ²​`5% квантиль`,
#   ³​`95% квантиль`</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что гости, которые посещают спа-центр разово, более склонны нарушать правила клуба. Стандартное отклонение посещения - 53.8 минуты, а среднее 86.6 минут.</p>
<p>Мы проделаем туже корректировку с данными, как это было с абонементами гуппы <code>А</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Среднее Медиана Стандартное_отклонение
    &lt;dbl&gt;   &lt;dbl&gt;                  &lt;dbl&gt;
1    81.8      77                   32.0</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что среднее изменилось не существенно и теперь равняется 81.8. На графике теперь видно, что большая часть посетителей укладывается в рамки 80-90 минут посещения.</p>
</section>
<section id="абонементы-группы-hard" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="абонементы-группы-hard">Абонементы группы <code>Hard</code></h4>
<p>Абонменты гурппы <code>Hard</code> неограничены во времени и включают в себя как посещения бассейна, так и посещения банного комплекса. Наша гипотеза заключалась в том, что гости не будут находиться в комплексе в среднем более 3 часов <em>(180 минут)</em>.</p>
<p>Сейчас мы посмотрим как распределено время посещения по всем абонеметам типа <code>Hard</code>. Далее посмотрим каждый абонемент в отдельности.</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Заметка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Данные абонементы имеют выбросы. Много крайне низких и высоких значений<em>.</em> Мы понимаем, что это по большой части ошибки, связанные с разными причинами. Давайте посмотрим на квантили распредения и очистим наши данные от критических значений. В нашем случае Q1 будет равняться 5%, а Q4 - 95% данным.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
     Q1    Q4
  &lt;dbl&gt; &lt;dbl&gt;
1    59   192</code></pre>
</div>
</div>
<p>Мы видим, что 95% данных лежит в переделе 192 минут, то есть все остальные значения, которые больше 192 минут, характерны только для 5% случаев. 5% данных имеют показателоь менее 59 минут.</p>
<p>Исходя из вышесказанного мы отсечем все данные, которые менее <code>Q1</code> и не больше <code>Q4</code> и построим график распредлеения.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Среднее Медиана Стандартное_отклонение
    &lt;dbl&gt;   &lt;dbl&gt;                  &lt;dbl&gt;
1    110.     105                   31.7</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Мы видим, что основная доля посещений лежит левее среднего, то есть мы можем заключить, что наша гиппотеза оказалась ошибочной, правда, в нашу пользу.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Начало работы</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">Ногинск 2022, Костыря Владимир</div>
  </div>
</footer>



</body></html>